import { readFile } from "fs/promises";
import { join } from "path";
import { homedir } from "os";

// Catalog of startable local models, generated by
// ~/models/scripts/write-models-catalog.sh and read here per-request.
//
// It lives in ~/.pi/agent/ rather than in this repo on purpose: that directory
// is already tracked in the pi config repo and already bind-mounted into the
// server's pi-web container, so adding a model on the desktop reaches every
// install through the existing `sync-pi-config.sh` path — no image rebuild.
// Same pattern as pi-web-voice.json / lib/voice-settings.ts.
const CATALOG_PATH = join(homedir(), ".pi", "agent", "pi-web-local-models.json");

export type LocalModel = {
  command: string; // launcher symlink to spawn (e.g. "qwen27b", "artemis")
  alias: string;   // the -a alias llama-server reports at /v1/models
  label: string;
};

export type LocalModelCatalog = {
  mainPort: number;
  stop: string; // port-scoped stop command (every launcher's -stop kills :8080)
  models: LocalModel[];
};

// Used when the catalog file is missing entirely — a machine where the
// generator has never run. Deliberately empty rather than a stale hardcoded
// list: an empty list with an explanatory message in the UI is honest, a wrong
// list is not.
const EMPTY: LocalModelCatalog = {
  mainPort: 8080,
  stop: "qwen-stop",
  models: [],
};

function isValid(v: unknown): v is LocalModelCatalog {
  if (typeof v !== "object" || v === null) return false;
  const c = v as Partial<LocalModelCatalog>;
  if (!Array.isArray(c.models)) return false;
  if (typeof c.mainPort !== "number") return false;
  if (typeof c.stop !== "string") return false;
  return c.models.every(
    (m) =>
      typeof m?.command === "string" &&
      typeof m?.alias === "string" &&
      typeof m?.label === "string",
  );
}

export async function readLocalModelCatalog(): Promise<LocalModelCatalog> {
  try {
    const raw = await readFile(CATALOG_PATH, "utf-8");
    const parsed: unknown = JSON.parse(raw);
    if (!isValid(parsed)) {
      console.warn(`local-models: ${CATALOG_PATH} is malformed, ignoring`);
      return EMPTY;
    }
    return parsed;
  } catch (err) {
    const code = (err as NodeJS.ErrnoException)?.code;
    if (code !== "ENOENT") {
      console.warn(`local-models: could not read ${CATALOG_PATH}:`, err);
    }
    return EMPTY;
  }
}
